updating devel scripts and man page

diff --git a/devel/build_install_pyradio b/devel/build_install_pyradio
--- a/devel/build_install_pyradio
+++ b/devel/build_install_pyradio
@@ -1,18 +1,32 @@
 #!/bin/bash
-while [[ $# -gt 0 ]]
-do
-    key="$1"
-    case $key in
-        -h|--help)
-            echo "Usage: $0 [2/3]
+help(){
+echo "Usage: $0 [2/3]
 
 Available options:
   2  build using python v. 2.x
   3  build using python v. 3.x
 
-If no option is used, will build using
-system default python
-"
+If no option is used, will build using system default 
+
+Checking python availability:"
+
+            for n in "" 2 3;do
+                echo -n "  python${n}"
+                [ -z "$n" ] && echo -n " "
+                echo -n "   ...   "
+                python${n} --version 2>/dev/null 1>&2 && {
+                    python${n} --version
+                } || echo not found
+            done
+            echo
+}
+
+while [[ $# -gt 0 ]]
+do
+    key="$1"
+    case $key in
+        -h|--help)
+            help
             exit
             ;;
         2)
@@ -31,14 +45,28 @@ system default python
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
+# check dependencies :)
+for prog in git sed ;do
+    ${prog} --version 2>/dev/null 1>&2 || {
+        echo "Error: ${prog} not found."
+        echo "       Please install it and try again."
+        exit 1
+    }
+done
+
 # delete any files that were left from previous attempt
 sudo find . -iname "*.pyc" -delete 2>/dev/null
 sudo find . -iname "*.egg" -delete 2>/dev/null
 
-descr=$(git describe --long --tags 2>/dev/null)
+# add git repo info to project
+descr=$(git describe --long --tags 2>/dev/null || echo not_from_git)
 [ -z "$descr" ] || sed -i "s/git_description = ''/git_description = '${descr}'/" pyradio/radio.py
+
+# build and install project
 python"${TO_PYTHON}" setup.py build && {
 echo "***** installing..."
 sudo python"${TO_PYTHON}" setup.py install 
 }
+
+# restore files to original state
 [ -z "$descr" ] || sed -i "s/git_description = '[^']*'/git_description = ''/" pyradio/radio.py
diff --git a/devel/pre-commit b/devel/pre-commit
--- a/devel/pre-commit
+++ b/devel/pre-commit
@@ -1,8 +1,17 @@
 #!/bin/bash
-[ -z "$(git status | grep 'modified:' | grep README.md)" ] || {
+set -x
+for afile in README.md build.md
+do
+#[ -z "$(git status | grep ${afile})" ] || {
+[ -z "$(git status | grep 'modified:' | grep ${afile})" ] || {
+    out=${afile/%.md/.html}
     echo '% PyRadio README' > tmp.md
-    cat README.md >> tmp.md
-    pandoc -s -t html tmp.md -o README.html || exit 1
+    cat ${afile} >> tmp.md
+    pandoc -s -t html tmp.md -o ${out} || {
+        echo "Error: pandoc not found"
+        rm tmp.md
+        exit 1
+    }
     sed -i '/<style /a \
     html {margin: 2em;} \
     h2 {margin-top: 2.5em; border-bottom:1px solid #D6D6D6;} \
@@ -10,15 +19,16 @@
     dl {margin: 2em;} \
     dd {margin: 1em;} \
     dt {font-weight: bold;} \
-    pre { background-color: #F6F6F6; padding: 1.5em; border: 1px solid #E6E6E6;}' README.html
+    pre { background-color: #F6F6F6; padding: 1.5em; border: 1px solid #E6E6E6;}' ${out}
     sed -i -e 's/<code>//g' \
         -e 's{</code>{{g' \
         -e 's{<a href="#pyradio">pyradio</a>{[pyradio]{' \
         -e 's/<p><strong>Tip:/<p style="margin: 1.5em 4em 0 4em; text-indent: -2em;"><strong>Tip:/' \
         -e 's/<li><p>/<li>/g' \
         -e 's{</</p></li>{</li>{g' \
-        -e '/h1 class="title"/d' README.html
+        -e 's/\.md">/.html">/' \
+        -e '/h1 class="title"/d' ${out}
     rm tmp.md
-    git add README.html
+    git add ${out}
 }
-
+done
